
name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: sarathTechie
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Save graph
        run: |
          cp dist/github-contribution-grid-snake.svg ./github-contribution-grid-snake.svg
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update contribution snake" || exit 0
          git push
